apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: pradeep-dep
spec: # Dictionary
  replicas: 1
  selector:
    matchLabels:
      app: myapp3
  template:  
    metadata: # Dictionary
      name: mynew-pod
      labels: # Dictionary
        app: myapp3  # Key value paids
    spec:
      containers: # List
        - name: mynew-container
          image: asuuki.jfrog.io/pradeep-local/korversion:2.0.0
          ports: 
            - containerPort: 80  
      imagePullSecrets:
        - name: jfrog-mysecret     
    
