name : Build and Push Docker image to ACR
'on' : push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - run: |
          docker build -t Korversion:1.0.0 Applicationcode1
          
